package com.woleapp.network.soap.response;

import android.text.TextUtils;
import com.woleapp.util.Constants;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;

@Root(name = Constants.PN_RESPONSE)
public class FundsTransferResponse
{
    @Element(name = Constants.PN_DIRECTION)
    public String direction;

    @Element(name = Constants.PN_REFERENCE, required = false)
    /*unique transaction id generated by
    eTranzact for the transaction*/
    public String reference;

    @Element(name = Constants.PN_AMOUNT)
    public String amount;

    @Element(name = "totalFailed")
    /*compulsory for bulkTransfer operation, it
    contains the total number of failed transactions*/
    public String totalFailed;

    @Element(name = "totalSuccess")
    /*compulsory for bulkTransfer operation, it
    contains the total number of failed transactions*/
    public String totalSuccess;

    @Element(name = "error")
    public int error;

    @Element(name = Constants.PN_MESSAGE)
    public String message;

    @Element(name = "otherReference")
    public String otherReference;

    @Element(name = Constants.PN_ACTION)
    public String action;

    @Element(name = "openingBalance")
    public double openingBalance;

    @Element(name = "closingBalance")
    public double closingBalance;


    public String getDirection() {
        return direction;
    }

    public void setDirection(String direction) {
        this.direction = direction;
    }

    public String getReference() {
        return reference;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getTotalFailed() {
        return totalFailed;
    }

    public void setTotalFailed(String totalFailed) {
        this.totalFailed = totalFailed;
    }

    public String getTotalSuccess() {
        return totalSuccess;
    }

    public void setTotalSuccess(String totalSuccess) {
        this.totalSuccess = totalSuccess;
    }

    public int getError() {
        return error;
    }

    public void setError(int error) {
        this.error = error;
    }

    public String getMessage() {
        return TextUtils.isEmpty(message)?"":message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getOtherReference() {
        return TextUtils.isEmpty(otherReference)?"":otherReference;
    }

    public void setOtherReference(String otherReference) {
        this.otherReference = otherReference;
    }

    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public double getOpeningBalance() {
        return openingBalance;
    }

    public void setOpeningBalance(double openingBalance) {
        this.openingBalance = openingBalance;
    }

    public double getClosingBalance() {
        return closingBalance;
    }

    public void setClosingBalance(double closingBalance) {
        this.closingBalance = closingBalance;
    }
}
